# Generated by Django 4.1.1 on 2022-10-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_graph_app', '0002_roundrank_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roundrank_count',
            new_name='roundrank_count_05_18',
        ),
    ]
