# Generated by Django 4.1.1 on 2022-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_graph_app', '0003_rename_roundrank_count_roundrank_count_05_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='roundrank_count_18_22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('round1', models.IntegerField()),
                ('round2', models.IntegerField()),
                ('round3', models.IntegerField()),
                ('round4', models.IntegerField()),
                ('round5', models.IntegerField()),
                ('round6', models.IntegerField()),
            ],
        ),
    ]
