# Generated by Django 4.1.1 on 2022-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_graph_app', '0004_roundrank_count_18_22'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('set_score', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='home_away_2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('home_away', models.CharField(max_length=50)),
                ('match_result', models.CharField(max_length=50)),
                ('match_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='home_away_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('home_away', models.CharField(max_length=50)),
                ('match_result', models.CharField(max_length=50)),
                ('match_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='relative_record_2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('match_result', models.CharField(max_length=50)),
                ('match_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='relative_record_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('match_result', models.CharField(max_length=50)),
                ('match_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seasonrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='upset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposing_team', models.CharField(max_length=50)),
                ('set_score', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
