# Generated by Django 4.1.1 on 2022-10-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_graph_app', '0005_clean_sheet_home_away_2021_home_away_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('toprankingpoint', models.FloatField()),
                ('match_count', models.IntegerField()),
                ('set_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('mistake', models.IntegerField()),
                ('attack_trial', models.IntegerField()),
                ('attack_success', models.IntegerField()),
                ('attack_block', models.IntegerField()),
                ('attack_mistake', models.IntegerField()),
                ('serve_trial', models.IntegerField()),
                ('serve_success', models.IntegerField()),
                ('serve_mistake', models.IntegerField()),
                ('set_trial', models.IntegerField()),
                ('set_success', models.IntegerField()),
                ('blocking_trial', models.IntegerField()),
                ('blocking_success', models.IntegerField()),
                ('blocking_mistake', models.IntegerField()),
                ('receive_trial', models.IntegerField()),
                ('receive_exact', models.IntegerField()),
                ('receive_fail', models.IntegerField()),
                ('dig_trial', models.IntegerField()),
                ('dig_success', models.IntegerField()),
            ],
        ),
    ]
